- import_tasks: pg_install.yml
- import_tasks: pg_passwd.yml
- import_tasks: pg_config.yml
- import_tasks: pg_hba.yml

- meta: flush_handlers

- name: ensure postgresql is running
  systemd:
    name: postgresql-{{pg_version}}
    state: started
    enabled: yes
    daemon_reload: yes
  when:
  - pg_version in pg_versions
