- name: config postgresql listen addresses
  lineinfile:
    path: "{{pg_data}}/postgresql.conf"
    regexp: '^listen_addresses\s*='
    insertafter: '^#listen_addresses\s*='
    line: "listen_addresses = '{{pg_listen_addresses}}'"
  notify:
  - restart pg

- name: config postgresql listen port
  lineinfile:
    path: "{{pg_data}}/postgresql.conf"
    regexp: '^port\s*='
    insertafter: '^#port\s*='
    line: "port = {{pg_listen_port}}"
  notify:
  - restart pg
