- name: config pg_hba.conf - host all all 0.0.0.0/0 scram-sha-256
  lineinfile:
    path: "{{pghba}}"
    line: "host    all             all             0.0.0.0/0               scram-sha-256"
    state: present
  notify:
  - restart pg
