- name: change the password for the postgres
  become: true
  become_user: postgres
  postgresql_user:
    name: "postgres"
    password: "{{pg_root_password}}"
  environment:
    PGOPTIONS: "-c password_encryption=scram-sha-256"
