---
- name: config gitlab external-url
  lineinfile:
    path: "{{gitlab_config}}"
    regexp: "^external_url\\s+"
    line: "external_url '{{gitlab_external_url}}'"
  notify: gitlab-reconfig
  when:
    - gitlab_external_url is defined
    - gitlab_external_url is regex('^http://') or gitlab_external_url is regex('^https://')

- name: config gitlab ssl certs
  block:
    - name: get domain name
      set_fact:
        gitlab_domain_name: "{{gitlab_external_url | split('//') | last }}"

    - name: create ssl directory
      file:
        path: /etc/gitlab/ssl
        state: directory
        owner: root
        group: root
        mode: 0755
    
    - name: write ssl cert
      copy:
        dest: /etc/gitlab/ssl/{{gitlab_domain_name}}.crt
        content: "{{ lookup('file', gitlab_ssl_cert) }}"
        owner: root
        group: root
        mode: 0644

    - name: write ssl key
      copy:
        dest: /etc/gitlab/ssl/{{gitlab_domain_name}}.key
        content: "{{ lookup('file', gitlab_ssl_key) }}"
        owner: root
        group: root
        mode: 0644

    - name: config gitlab nginx ssl cert
      lineinfile:
        path: "{{gitlab_config}}"
        regexp: "^nginx\\['ssl_certificate'\\]\\s+"
        insertafter: "^#nginx\\['ssl_certificate'\\]\\s+"
        line: "nginx['ssl_certificate'] = \"/etc/gitlab/ssl/{{gitlab_domain_name}}.crt\""

    - name: config gitlab nginx ssl key
      lineinfile:
        path: "{{gitlab_config}}"
        regexp: "^nginx\\['ssl_certificate_key'\\]\\s+"
        insertafter: "^#nginx\\['ssl_certificate_key'\\]\\s+"
        line: "nginx['ssl_certificate_key'] = \"/etc/gitlab/ssl/{{gitlab_domain_name}}.key\""
  when:
    - gitlab_external_url is defined
    - gitlab_external_url is regex('^http://') or gitlab_external_url is regex('^https://')
    - gitlab_ssl_cert is defined
    - gitlab_ssl_cert is not none
    - gitlab_ssl_key is defined
    - gitlab_ssl_key is not none
  notify: gitlab-reconfig