---
- name: install dependency packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - policycoreutils-python
    - openssh-server

- name: render gitlab-ee repo
  template:
    src: rhel-gitlab-ee.repo.j2
    dest: /etc/yum.repos.d/gitlab-ee.repo
    owner: root
    group: root
    mode: 0644

- name: install gitlab-ee
  yum:
    name: gitlab-ee
    state: present

- name: set facts
  set_fact:
    gitlab_config: /etc/gitlab/gitlab.rb

- name: include gitlab config
  include_tasks: config.yaml

- meta: flush_handlers

- name: enable gitlab service
  service:
    name: gitlab-runsvdir
    state: started
    enabled: yes
