---
- hosts: all
  gather_facts: false
  roles:
    - role: authorized_key
      vars:
        
        users:
          - name: zhanghe5
            key_from: file
            key: "~/.ssh/id_rsa.pub"
            state: present
          
