- hosts: all
  become: true
  gather_facts: true
  roles:
  - role: authorized_key
    tags:
    - authorized_key
    vars:
      users:
      - username: root
        state: present
        key_from: file
        key: ~/.ssh/id_rsa.pub
  - role: system-init
    tags:
    - system-init
    vars:
      disable_password_authentication: no
      permit_root_login: yes
  - role: chrony
    tags:
    - chrony


- hosts: 172.16.158.51
  gather_facts: true
  become: true
  become_user: root
  roles:
  - role: postgresql
    tags: postgresql, pgsql, pgsql15

- hosts: vault
  gather_facts: true
  become: true
  become_user: root
  roles:
  - role: vault
    tags: vault
    vars:
      pg_host: "172.16.158.51"
      pg_user: postgres
      pg_password: "PostgreSql123$"
      pg_port: 5432
      vault_db_name: vault
      vault_db_user: vault
      vault_db_user_password: "Vault123$"
      vault_db_created: true
      vault_table_created: true
      vault_user_created: true
      vault_init_exec: true
      vault_unseal_exec: true
      vault_unseal_keys: []


- hosts: 172.16.158.51
  become: true
  become_user: root
  roles:
  - role: kong
    tags: kong
    vars:
      kong_db_host: "172.16.158.51"
      kong_db_port: 5432
      kong_db_name: kong
      kong_db_user: kong
      kong_db_password: "Kong123$"
      konga_db_host: "172.16.158.51"
      konga_db_port: 5432
      konga_db_name: konga
      konga_db_user: konga
      konga_db_password: "Konga123$"
      kong_proxy_http_listen_port: 80
      kong_proxy_https_listen_port: 443
      kong_admin_http_listen_address: 0.0.0.0
      kong_admin_https_listen_address: 127.0.0.1
