- hosts: all
  become: true
  gather_facts: true
  roles:
  - role: authorized_key
    tags:
    - authorized_key
    vars:
      users:
      - username: root
        state: present
        key_from: file
        key: ~/.ssh/id_rsa.pub
  - role: system-init
    tags:
    - system-init
    vars:
      disable_password_authentication: no
      permit_root_login: yes
  - role: chrony
    tags:
    - chrony


- hosts: 172.16.158.51
  gather_facts: true
  become: true
  become_user: root
  roles:
  - role: postgresql
    tags: postgresql, pgsql, pgsql15
