- name: copy nodejs yum repo
  copy:
    src: nodejs.repo
    dest: /etc/yum.repos.d/nodejs.repo
    owner: root
    group: root
    mode: 0644

- name: install packages for konga
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - git
  - nodejs

- name: install gloal packages for nodejs
  npm:
    name: "{{ item }}"
    state: present
    global: yes
    registry: http://registry.npm.taobao.org
  with_items:
  - bower
  - gulp

- name: create konga data directory
  file:
    path: /data/konga
    state: directory
    owner: root
    group: root
    mode: 0755

- name: check konga code status
  stat:
    path: /data/konga/package.json
  register: konga_code_status

- name: clone konga code
  git:
    # use ghproxy proxy
    repo: https://ghproxy.com/https://github.com/pantsel/konga.git
    dest: /data/konga
    clone: yes
    version: master
  when: not konga_code_status.stat.exists

- name: check konga node_modules status
  stat:
    path: /data/konga/node_modules
  register: konga_node_modules_status

- name: install gloal packages for konga
  npm:
    path: /data/konga
    state: present
    registry: http://registry.npm.taobao.org
  when: not konga_node_modules_status.stat.exists

- name: render konga config file
  template:
    src: konga.j2
    dest: /data/konga/.env
    owner: root
    group: root
    mode: 0644

- name: init konga database
  shell: node /data/konga/bin/konga.js prepare --adapter postgres --uri postgresql://{{konga_db_user}}:'{{konga_db_password}}'@{{konga_db_host|default(kong_db_host)}}:{{konga_db_port|default(kong_db_port)}}/{{konga_db_name|default('konga')}}


# - name: start konga
