# tasks file for miniconda3
- name: set miniconda3 facts
  set_fact:
    miniconda3_script_filename: "/tmp/miniconda3.sh"
    miniconda3_install_dir: "{{miniconda3_install_parent_dir}}/miniconda3"

- name: register miniconda3 bin directory variable
  stat:
    path: "{{miniconda3_install_dir}}/bin"
  register: miniconda3_bin_dir_stat

- name: wget miniconda3 install script
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: "{{miniconda3_script_filename}}"
    mode: 0755
  when: not miniconda3_bin_dir_stat.stat.exists

- name: register miniconda3 script filename variable
  stat:
    path: "{{miniconda3_script_filename}}"
  register: miniconda3_script_filename_stat

- name: create miniconda3 install parent directory when it not exists
  file:
    path: "{{miniconda3_install_parent_dir}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: install miniconda3 to {{miniconda3_install_dir}}
  shell:
    cmd: "{{miniconda3_script_filename}} -b -u -p {{miniconda3_install_dir}}"
    executable: /bin/bash
  when: not miniconda3_bin_dir_stat.stat.exists
  notify:
  - update bashrc

- name: render miniconda3 profile config
  template:
    src: miniconda3.sh.j2
    dest: "/etc/profile.d/miniconda3.sh"
    owner: root
    group: root
    mode: 0644

- name: delete miniconda3 install script
  file:
    path: "{{miniconda3_script_filename}}"
    state: absent
  when: miniconda3_script_filename_stat.stat.exists
