---
- name: install and config docker-ce for redhat 7 family
  block:
    - name: install docker-ce for redhat 7 family
      import_tasks: docker_install.yaml

    - name: config docker-ce for redhat 7 family
      import_tasks: docker_config.yaml
  when:
    - ansible_facts.os_family.lower() == 'redhat'
    - ansible_facts.distribution_major_version == '7'