---
- name: copy yum repository
  template:
    src: redhat.repo.j2
    dest: /etc/yum.repos.d/salt.repo
    owner: root
    group: root
    mode: 0644

# salt master
- name: install and config saltstack master
  block:
    - name: install saltstack packages [salt-master]
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - salt-master
        - salt-minion
        - salt-ssh
        - salt-syndic
        - salt-cloud
        - salt-api

    - name: config salt master
      include_tasks: saltmaster-config.yaml
  when:
    - salt_role is not none
    - salt_role | lower == "master"

# salt minion
- name: install and config saltstack minion
  block:
    - name: install saltstack packages [salt-minion]
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - salt-minion
    
    - name: include salt minion config
      include_tasks: saltminion-config.yaml
  when:
    - salt_role is not none
    - salt_role | lower == "minion"
