- name: check mariadb version
  debug:
    msg: "mariadb version {{mariadb_version}} is not supported, supported versions: {{mariadb_supported_versions}}"
  failed_when: mariadb_version not in mariadb_supported_versions
  changed_when: false
  when: mariadb_version not in mariadb_supported_versions

- name: copy mariadb repository
  template:
    src: redhat_mariadb_repo.j2
    dest: /etc/yum.repos.d/mariadb.repo
    owner: root
    group: root
    mode: "0644"

- name: install mariadb server
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - MariaDB-server
    - MariaDB-client

- name: include mariadb configs
  include_tasks: configs.yaml
