---
- name: install ntpd package for redhat family
  yum:
    name: ntp
    state: present
  when:
    - ansible_facts.os_family.lower() == 'redhat'

- name: install ntpd package for debian family
  apt:
    name: ntp
    state: present
    update_cache: yes
  when:
    - ansible_facts.os_family.lower() == 'debian'

- name: copy ntpd config for aliyun ecs
  copy:
    src: aliyun_ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart ntpd
  when:
    - "'alibaba' in ansible_facts.product_name.lower()"

- name: copy ntpd config for other platform
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart ntpd
  when:
    - "'alibaba' not in ansible_facts.product_name.lower()"

- block:
    - name: ensure ntpd is running for redhat family
      service:
        name: ntpd
        state: started
        enabled: yes
  rescue:
    - name: ensure ntpd is running for debian family
      service: 
        name: ntp
        state: started
        enabled: yes
