# tasks file for roles/vault
- import_tasks: vault_pre.yml

- import_tasks: vault_db.yml
  when: vault_db_created | bool

- import_tasks: vault_user.yml
  when: vault_user_created | bool

- import_tasks: vault_table.yml

- import_tasks: vault_install.yml

- import_tasks: vault_config.yml

- meta: flush_handlers

- name: ensure vault is running
  service:
    name: vault
    state: started
    enabled: yes

- import_tasks: vault_init.yml
  when: vault_init_exec | bool

- import_tasks: vault_unseal.yml
  when: vault_unseal_exec | bool
