- name: copy postgresql yum repo
  copy:
    src: pgsql.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: install dependencies packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
  - python2-psycopg2
