redis_config_filename: '/etc/redis.conf'
redis_version: 'latest'
redis_listen_address: '0.0.0.0'
redis_port: 6379
redis_maxclients: 0
redis_maxmemory: ''
redis_password: ''
redis_databases: 16
redis_dir: '/var/lib/redis'
redis_dbfilename: 'dump.rdb'
redis_appendonly: yes
redis_appendfilename: 'appendonly.aof'
redis_appendfsync: 'everysec'