---
- name: started php72-php-fpm
  service:
    name: php72-php-fpm
    state: started
    enabled: yes
  when:
    - php72_service_start is defined
    - php72_service_start | bool

- name: stopped and disable php72-php-fpm
  service:
    name: php72-php-fpm
    state: stopped
    enabled: no
  when:
    - php72_service_start is defined
    - not (php72_service_start | bool)
