---
- name: install dependencies packages
  package:
    name: "{{item}}"
    state: present
  with_items:
    - openssl
    - openssl-devel
    - python2-PyMySQL

- name: include nginx config
  import_tasks: zabbix-nginx.yml

- name: copy zabbix repo
  copy:
    src: zabbix.repo
    dest: /etc/yum.repos.d/zabbix.repo
    owner: root
    group: root
    mode: 0644

- name: install zabbix server and agent
  package:
    name: "{{item}}"
    state: present
  with_items:
    - zabbix-server-mysql
    - zabbix-agent
    - zabbix-agent2
    - zabbix-get
    - zabbix-sender
    - zabbix-web

- name: import zabbix database config
  import_tasks: zabbix-server-db.yml
  when: not (zabbix_external_database | bool)

- name: import zabbix server config
  import_tasks: zabbix-server-config.yml
  notify: restart zabbix-server

- name: ensure zabbix server is running
  service:
    name: zabbix-server
    state: started
    enabled: yes
