---
- name: install dependencies packages
  package:
    name: "{{item}}"
    state: present
  with_items:
    - openssl
    - openssl-devel
    - httpd
    - httpd-devel

- name: copy zabbix repo
  copy:
    src: zabbix.repo
    dest: /etc/yum.repos.d/zabbix.repo
    owner: root
    group: root
    mode: 0644
