# defaults file for roles/kong
kong_db_host: 127.0.0.1
kong_db_port: 5432
kong_db_name: kong
kong_db_user: kong
konga_db_host: 127.0.0.1
konga_db_port: 5432
konga_db_name: konga
konga_db_user: konga
kong_proxy_http_listen_address: 0.0.0.0
kong_proxy_http_listen_port: 8000
kong_proxy_http_listen_backlog: 16384
kong_proxy_https_listen_address: 0.0.0.0
kong_proxy_https_listen_port: 8443
kong_proxy_https_listen_backlog: 16384
kong_admin_http_listen_address: 0.0.0.0
kong_admin_http_listen_port: 8001
kong_admin_http_listen_backlog: 16384
kong_admin_https_listen_address: 0.0.0.0
kong_admin_https_listen_port: 8444
kong_admin_https_listen_backlog: 16384
