---
- block:
  - name: restart ntpd
    service:
      name: ntpd
      state: restarted
      enabled: true
  rescue:
    - name: restart ntpd
      service:
        name: ntp
        state: restarted
        enabled: true
